### ISSUE TITLE
Nightly feature?

### ISSUE THREAD

**Issue by andre-richter** [rust-embedded/cortex-a#39]
CC @AGSaidi since this is blocking the release of https://github.com/rust-embedded/cortex-a/pull/38.

Hi @qwandor,

I am in the process of doing a new release (to make https://github.com/rust-embedded/cortex-a/pull/38 public). However, I have a question regarding your PR https://github.com/rust-embedded/cortex-a/pull/37. 
When I build with with stable Rust using
```
cargo build --target aarch64-unknown-none-softfloat --no-default-features
```

it errors out on the the core intrinsics use in asm.rs:
```
error[E0658]: use of unstable library feature 'core_intrinsics': intrinsics are unlikely to ever be stabilized, instead they should be used through stabilized interfaces in the rest of the standard library
  --> src/asm.rs:96:9
   |
96 |         core::intrinsics::unreachable()
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add `#![feature(core_intrinsics)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'core_intrinsics': intrinsics are unlikely to ever be stabilized, instead they should be used through stabilized interfaces in the rest of the standard library
   --> src/asm.rs:111:9
    |
111 |         core::intrinsics::unreachable()
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add `#![feature(core_intrinsics)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `cortex-a` due to 2 previous errors
```

Did you not stumble over these back then, or am I doing something wrong?

**Comment by qwandor** [comment]
I don't remember having an issue with that, but I'll have a look on Monday.

**Comment by andre-richter** [comment]
I have guarded the functions for now as well (https://github.com/rust-embedded/cortex-a/commit/c5964a2c210518584f5b2e8aff4c6a54f7db6d0a). Could be worth a thought to only guard the `unreachable`. We can do this in a follow up release if there is demand.

**Comment by qwandor** [comment]
Well I can reproduce the issue, so I'm not sure how I missed it before.

Would it be possible to use [`core::unreachable`](https://doc.rust-lang.org/core/macro.unreachable.html) rather than `core::intrinsics::unreachable`? Or [`core::hint::unreachable_unchecked`](https://doc.rust-lang.org/core/hint/fn.unreachable_unchecked.html) if you prefer.

**Comment by andre-richter** [comment]
Since we already have an unsafe block open, let’s go with the unchecked. Can you post a PR?

I can publish it as a patch release tonight.

**Comment by andre-richter** [comment]
Thanks!
