### ISSUE TITLE
[Question] BeagleBone Black Support

### ISSUE THREAD

**Issue by shaggygi** [rust-embedded/cortex-a#43]
Hi, I'm new to this space and came across this repo.  Does this have support for BeagleBone Black?  If so, do you have any samples to possibly get noobs started?  Thanks for any info.

**Comment by andre-richter** [comment]
This is a processor support crate, it seems you are more looking for a board support crate like in https://github.com/rust-embedded/awesome-embedded-rust#board-support-crates

**Comment by shaggygi** [comment]
@andre-richter oops.  thanks for the link.  i'll add in that repo.

**Comment by shaggygi** [comment]
@andre-richter  So there was some discussions about this over on the BeagleBoard forums and it was pointed out this doesn't currently support AArch32.  Any plans on adding so it might possibly support the AM355x used on BBB?  Thx again.

**Comment by andre-richter** [comment]
No plans from my side to add AArch32 support.
But we’re always happy to take PRs.
