### ISSUE TITLE
Supporting 32 bit for cortex-a

### ISSUE THREAD

**Issue by imukherjee-sndk** [rust-embedded/cortex-a#44]
I have a system that's running A53 arm core in 32 bit mode. I'm interested in integrating Rust into this environment.
If I understand correctly, this project currently supports only 64-bit cortex-a. Can someone guide me as to what support is required to get 32 bit supported? I might give it a shot... thanks!

**Comment by andre-richter** [comment]
Closing. This crate has been renamed and moved to https://github.com/rust-embedded/aarch64-cpu and will not consider AArch32.
