### ISSUE TITLE
Export upstream memory barrier functions

### ISSUE THREAD

**Issue by andre-richter** [rust-embedded/cortex-a#5]
Reexport memory barrier funcs from https://github.com/rust-lang-nursery/stdsimd/pull/557

**Comment by rahealy** [comment]
Most of this is new to me but I think these are documented here:

https://doc.rust-lang.org/core/arch/arm/index.html
https://doc.rust-lang.org/core/arch/aarch64/index.html

If these are the correct dependencies would you prefer putting the re-exports in barriers.rs or removing barriers.rs and putting the re-exports into lib.rs?

**Comment by andre-richter** [comment]
I gave this a shot some time ago, but memory fails me a bit.
I think re-exporting those had the unpleasant side effect that users of cortex-a then would need to add some experimental intrinsics global attribute to their top level file.

That's a bit against the intention of the crate for taking care of these hassles for the user.

Let me have a look again if the re-exporting is feasible under these circumstances and come back to you soon!

Thanks,
Andre

**Comment by andre-richter** [comment]
Closing this for now since I lost track of it and don't have resources to implement this at the moment.
