### ISSUE TITLE
ERET Opcode

### ISSUE THREAD

**Issue by rahealy** [rust-embedded/cortex-a#9]
I'm currently researching changing from EL2 to EL1 on a RaspberryPi 3 (Cortex-A53, AArch64).

I'm using the example found on this stackoverflow post for a starting point:
https://stackoverflow.com/questions/46194098/armv8-changing-from-el3-to-el1-secure

The cortex-a package provides all the necessary register mappings (thank you very much for that). I was wondering if there's a cortex-a library specific way to handle the necessary ERET opcode or if I should just use `asm!("ERET");`?

**Comment by andre-richter** [comment]
Hi @rahealy,

it's implemented here: https://github.com/rust-embedded/cortex-a/blob/master/src/asm.rs#L49

For what you are currently experimenting with, you might find this one interesting: https://github.com/rust-embedded/rust-raspi3-OS-tutorials/tree/master/0C_exception_levels :smile: 

You'll find a whole bunch of other RPi3 Rust goodness there. Note that I am currently rewriting the tutorials, so progress on the main branch is a bit stalled, but stuff is relevant nonetheless.

Best,
Andre

**Comment by rahealy** [comment]
Thank you very much for the help.

I used a case sensitive grep for 'ERET' while looking through the library code. :expressionless: 

The tutorials are awesome. I worked through and made use of the simpler topics already. Thanks for the encouragement - I will work through "11_exceptions_groundwork" and "0C_exception_levels".

Appreciatively,

-Richard
